import React, { useRef } from 'react';

/**
 * PrescriptionQRModal
 *
 * Shown after a prescription is saved and validated.
 * Displays the QR code and provides Download + Print actions.
 *
 * Props:
 *   prescriptionId  — e.g. "PR00001"
 *   validatedAt     — ISO date string
 *   qrCodeData      — base64 PNG data URL
 *   patientName     — display name
 *   patientPhn      — PHN string
 *   doctorName      — display name
 *   medicines       — string[]
 *   onClose         — () => void
 */
const PrescriptionQRModal = ({
  prescriptionId,
  validatedAt,
  qrCodeData,
  patientName,
  patientPhn,
  doctorName,
  medicines = [],
  onClose,
}) => {
  const printRef = useRef(null);

  const handleDownload = () => {
    const link = document.createElement('a');
    link.href = qrCodeData;
    link.download = `prescription-${prescriptionId}-qr.png`;
    link.click();
  };

  const handlePrint = () => {
    const printWindow = window.open('', '_blank', 'width=600,height=700');
    const validDate = validatedAt
      ? new Date(validatedAt).toLocaleDateString()
      : 'N/A';
    const medicineList = medicines
      .map((m) => `<li>${m}</li>`)
      .join('');

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>Prescription ${prescriptionId}</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 24px; color: #111; }
            h2  { margin-bottom: 4px; }
            .badge { display:inline-block; background:#1a7f37; color:#fff; padding:2px 10px;
                     border-radius:12px; font-size:12px; font-weight:bold; margin-bottom:12px; }
            table { width:100%; border-collapse:collapse; margin-top:12px; }
            td, th { padding:6px 8px; border:1px solid #ddd; font-size:13px; }
            th { background:#f5f5f5; }
            .qr { text-align:center; margin-top:16px; }
            .qr img { width:180px; height:180px; }
            .footer { margin-top:16px; font-size:11px; color:#888; text-align:center; }
          </style>
        </head>
        <body>
          <h2>MediEase Prescription</h2>
          <span class="badge">VALIDATED</span>
          <table>
            <tr><th>Prescription ID</th><td>${prescriptionId}</td></tr>
            <tr><th>Patient</th><td>${patientName} (${patientPhn})</td></tr>
            <tr><th>Doctor</th><td>${doctorName}</td></tr>
            <tr><th>Validated On</th><td>${validDate}</td></tr>
          </table>
          <h4 style="margin-top:16px">Medicines</h4>
          <ul>${medicineList}</ul>
          <div class="qr">
            <img src="${qrCodeData}" alt="Prescription QR Code" />
            <p style="font-size:12px;color:#555">Scan to verify authenticity</p>
          </div>
          <p class="footer">Generated by MediEase EMR System</p>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    printWindow.print();
    printWindow.close();
  };

  const validDate = validatedAt
    ? new Date(validatedAt).toLocaleString()
    : 'Just now';

  return (
    <div className="modal-overlay" role="dialog" aria-modal="true">
      <div className="modal-content" style={{ maxWidth: 480 }}>
        {/* Header */}
        <div className="modal-header">
          <h3>Prescription Validated</h3>
          <button className="modal-close-btn" onClick={onClose} aria-label="Close">×</button>
        </div>

        {/* Body */}
        <div className="modal-body" ref={printRef}>
          {/* Status badge */}
          <div style={{ marginBottom: 12 }}>
            <span style={{
              display: 'inline-block',
              background: '#1a7f37',
              color: '#fff',
              padding: '3px 14px',
              borderRadius: 12,
              fontSize: 13,
              fontWeight: 'bold',
              letterSpacing: 1,
            }}>
              VALIDATED
            </span>
          </div>

          {/* Meta */}
          <div style={{ fontSize: 13, marginBottom: 12, lineHeight: 1.7 }}>
            <div><strong>Prescription ID:</strong> {prescriptionId}</div>
            <div><strong>Patient:</strong> {patientName} ({patientPhn})</div>
            <div><strong>Doctor:</strong> {doctorName}</div>
            <div><strong>Validated at:</strong> {validDate}</div>
          </div>

          {/* QR Image */}
          {qrCodeData && (
            <div style={{ textAlign: 'center', margin: '16px 0' }}>
              <img
                src={qrCodeData}
                alt="Prescription QR Code"
                style={{ width: 220, height: 220, border: '1px solid #eee', borderRadius: 8 }}
              />
              <p style={{ fontSize: 11, color: '#888', marginTop: 4 }}>
                Scan to verify prescription authenticity
              </p>
            </div>
          )}
        </div>

        {/* Footer actions */}
        <div className="modal-footer" style={{ display: 'flex', justifyContent: 'flex-end', gap: 8 }}>
          <button className="action-btn secondary" onClick={handleDownload}>
            Download QR
          </button>
          <button className="action-btn secondary" onClick={handlePrint}>
            Print Prescription
          </button>
          <button className="action-btn primary" onClick={onClose}>
            Done
          </button>
        </div>
      </div>
    </div>
  );
};

export default PrescriptionQRModal;
